import UIKit

class PDFGenerator {
    static func generateReceipt(for asset: Asset) -> Data {
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792) // Letter size
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        return renderer.pdfData { context in
            context.beginPage()

            let margin: CGFloat = 50
            var y: CGFloat = margin

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.boldSystemFont(ofSize: 24),
                .foregroundColor: UIColor.label
            ]
            let title = "StashBox — Asset Receipt"
            title.draw(at: CGPoint(x: margin, y: y), withAttributes: titleAttrs)
            y += 40

            // Divider
            context.cgContext.setStrokeColor(UIColor.separator.cgColor)
            context.cgContext.setLineWidth(1)
            context.cgContext.move(to: CGPoint(x: margin, y: y))
            context.cgContext.addLine(to: CGPoint(x: pageRect.width - margin, y: y))
            context.cgContext.strokePath()
            y += 20

            let labelAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 11),
                .foregroundColor: UIColor.secondaryLabel
            ]
            let valueAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 14, weight: .medium),
                .foregroundColor: UIColor.label
            ]

            func drawField(_ label: String, _ value: String) {
                label.draw(at: CGPoint(x: margin, y: y), withAttributes: labelAttrs)
                y += 16
                value.draw(at: CGPoint(x: margin, y: y), withAttributes: valueAttrs)
                y += 24
            }

            drawField("PRODUCT", asset.name)
            if !asset.brand.isEmpty { drawField("BRAND", asset.brand) }
            if !asset.model.isEmpty { drawField("MODEL", asset.model) }
            if !asset.serialNumber.isEmpty { drawField("SERIAL", asset.serialNumber) }
            drawField("CATEGORY", asset.category.displayName)
            drawField("PURCHASED", displayDate(asset.purchaseDate))
            drawField("PRICE", asset.priceDisplay)
            if !asset.retailer.isEmpty { drawField("RETAILER", asset.retailer) }

            y += 10
            context.cgContext.move(to: CGPoint(x: margin, y: y))
            context.cgContext.addLine(to: CGPoint(x: pageRect.width - margin, y: y))
            context.cgContext.strokePath()
            y += 20

            // Warranties
            if !asset.warranties.isEmpty {
                let sectionAttrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.boldSystemFont(ofSize: 16),
                    .foregroundColor: UIColor.label
                ]
                "WARRANTIES".draw(at: CGPoint(x: margin, y: y), withAttributes: sectionAttrs)
                y += 28

                for warranty in asset.warranties {
                    drawField(warranty.name, {
                        var parts: [String] = []
                        if warranty.isLifetime {
                            parts.append("Lifetime")
                        } else if let end = warranty.endDate {
                            parts.append("Expires: \(displayDate(end))")
                        }
                        if !warranty.coverageDetails.isEmpty {
                            parts.append(warranty.coverageDetails)
                        }
                        return parts.joined(separator: " · ")
                    }())
                }
            }

            // Service records
            if !asset.serviceRecords.isEmpty {
                y += 10
                let sectionAttrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.boldSystemFont(ofSize: 16),
                    .foregroundColor: UIColor.label
                ]
                "SERVICE RECORDS".draw(at: CGPoint(x: margin, y: y), withAttributes: sectionAttrs)
                y += 28

                for record in asset.serviceRecords {
                    let desc = record.description.isEmpty ? record.type.displayName : record.description
                    let cost = record.cost.map { String(format: "%.2f", $0) } ?? "—"
                    drawField("\(shortDate(record.date)) — \(desc)", "Cost: \(cost) | \(record.coveredByWarranty ? "Covered by warranty" : "Out of warranty")")
                }
            }

            // Footer
            y = pageRect.height - margin - 20
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 9),
                .foregroundColor: UIColor.tertiaryLabel
            ]
            "Generated by StashBox · \(displayDate(dateOnlyISO()))".draw(at: CGPoint(x: margin, y: y), withAttributes: footerAttrs)
        }
    }
}
